pm: workaround, temporarily disable calc_ddr_checksum
this cause build err:

In file included from arch/arm/include/generated/asm/sections.h:1:0,
                 from arch/arm/mach-owl/pm-owl.c:546:
include/asm-generic/sections.h:23:29: error: conflicting type qualifiers for ‘__nosave_begin’
 extern __visible const void __nosave_begin, __nosave_end;
                             ^
In file included from arch/arm/mach-owl/pm-owl.c:25:0:
arch/arm/mach-owl/include/mach/power.h:90:28: note: previous declaration of ‘__nosave_begin’ was here
 extern const unsigned long __nosave_begin[], __nosave_end[];
                            ^
In file included from arch/arm/include/generated/asm/sections.h:1:0,
                 from arch/arm/mach-owl/pm-owl.c:546:
include/asm-generic/sections.h:23:45: error: conflicting type qualifiers for ‘__nosave_end’
 extern __visible const void __nosave_begin, __nosave_end;
                                             ^
In file included from arch/arm/mach-owl/pm-owl.c:25:0:
arch/arm/mach-owl/include/mach/power.h:90:46: note: previous declaration of ‘__nosave_end’ was here
 extern const unsigned long __nosave_begin[], __nosave_end[];
                                              ^
scripts/Makefile.build:308: recipe for target 'arch/arm/mach-owl/pm-owl.o' failed
make[1]: *** [arch/arm/mach-owl/pm-owl.o] Error 1
Makefile:815: recipe for target 'arch/arm/mach-owl' failed